import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SearchBar from '@/Components/SearchBar'
import CoinList from '@/Components/CoinList'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({coinsData }) {
  const [searchData, setSearchData] = useState("");

  const filteredData = coinsData.filter((data)=>{
    return data.name.toLowerCase().includes(searchData.toLowerCase());
  })


  console.log(filteredData, "this is filtered data.");
  console.log(coinsData);

  const changeHandler = (e) =>{
    setSearchData(e.target.value);
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar type="text" placeholder="Search" onChange={changeHandler}/>
      <CoinList coinsData={filteredData}/>
    </>
  )
}

export const getServerSideProps = async () =>{
  const res = await fetch("https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false&locale=en")
  const coinsData = await res.json();
  return{
    props:{
      coinsData
    }
  }
}
